version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vfinance-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vfinance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vfinance"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vfinance-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: vfinance-api
    ports:
      - "3001:3000"
    environment:
      - API_PORT=3000
      - API_HOST=0.0.0.0
      - DATABASE_URL=postgres://user:password@postgres:5432/vfinance?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - ETHEREUM_RPC=http://147.93.11.54:8545
      - CONTRACT_ADDRESS=0x2dd1eda184bC63cD23aE7Fe71D7c8063C673781B
      - PRIVATE_KEY=0x595fff4bd0c4e716c1e439cd70a49f9d049fd0dd2a096e2a573dfb2e819c668c
      - JWT_SECRET=your_super_secret_key_here
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX=100
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: